// flow-typed signature: 75248c3c1054f5c5760a355e4dd3da16
// flow-typed version: <<STUB>>/palx_v1.0.2/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'palx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'palx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'palx/dist/flatten' {
  declare module.exports: any;
}

declare module 'palx/dist/hue-name' {
  declare module.exports: any;
}

declare module 'palx/dist/index' {
  declare module.exports: any;
}

declare module 'palx/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'palx/dist/flatten.js' {
  declare module.exports: $Exports<'palx/dist/flatten'>;
}
declare module 'palx/dist/hue-name.js' {
  declare module.exports: $Exports<'palx/dist/hue-name'>;
}
declare module 'palx/dist/index.js' {
  declare module.exports: $Exports<'palx/dist/index'>;
}
declare module 'palx/webpack.config.js' {
  declare module.exports: $Exports<'palx/webpack.config'>;
}
