// flow-typed signature: 0ec6b47dd09eac08ac761be37692bf60
// flow-typed version: <<STUB>>/styled-system_v1.1.4/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-system'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-system' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-system/dist/active' {
  declare module.exports: any;
}

declare module 'styled-system/dist/align-items' {
  declare module.exports: any;
}

declare module 'styled-system/dist/align-self' {
  declare module.exports: any;
}

declare module 'styled-system/dist/border-color' {
  declare module.exports: any;
}

declare module 'styled-system/dist/border-radius' {
  declare module.exports: any;
}

declare module 'styled-system/dist/border-width' {
  declare module.exports: any;
}

declare module 'styled-system/dist/box-shadow' {
  declare module.exports: any;
}

declare module 'styled-system/dist/clean-element' {
  declare module.exports: any;
}

declare module 'styled-system/dist/color' {
  declare module.exports: any;
}

declare module 'styled-system/dist/constants' {
  declare module.exports: any;
}

declare module 'styled-system/dist/disabled' {
  declare module.exports: any;
}

declare module 'styled-system/dist/flex-direction' {
  declare module.exports: any;
}

declare module 'styled-system/dist/flex-wrap' {
  declare module.exports: any;
}

declare module 'styled-system/dist/flex' {
  declare module.exports: any;
}

declare module 'styled-system/dist/focus' {
  declare module.exports: any;
}

declare module 'styled-system/dist/font-size' {
  declare module.exports: any;
}

declare module 'styled-system/dist/font-weight' {
  declare module.exports: any;
}

declare module 'styled-system/dist/hover' {
  declare module.exports: any;
}

declare module 'styled-system/dist/index' {
  declare module.exports: any;
}

declare module 'styled-system/dist/justify-content' {
  declare module.exports: any;
}

declare module 'styled-system/dist/letter-spacing' {
  declare module.exports: any;
}

declare module 'styled-system/dist/line-height' {
  declare module.exports: any;
}

declare module 'styled-system/dist/prop-types' {
  declare module.exports: any;
}

declare module 'styled-system/dist/pseudo-style' {
  declare module.exports: any;
}

declare module 'styled-system/dist/remove-props' {
  declare module.exports: any;
}

declare module 'styled-system/dist/responsive-style' {
  declare module.exports: any;
}

declare module 'styled-system/dist/space' {
  declare module.exports: any;
}

declare module 'styled-system/dist/style' {
  declare module.exports: any;
}

declare module 'styled-system/dist/text-align' {
  declare module.exports: any;
}

declare module 'styled-system/dist/theme' {
  declare module.exports: any;
}

declare module 'styled-system/dist/util' {
  declare module.exports: any;
}

declare module 'styled-system/dist/width' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-system/dist/active.js' {
  declare module.exports: $Exports<'styled-system/dist/active'>;
}
declare module 'styled-system/dist/align-items.js' {
  declare module.exports: $Exports<'styled-system/dist/align-items'>;
}
declare module 'styled-system/dist/align-self.js' {
  declare module.exports: $Exports<'styled-system/dist/align-self'>;
}
declare module 'styled-system/dist/border-color.js' {
  declare module.exports: $Exports<'styled-system/dist/border-color'>;
}
declare module 'styled-system/dist/border-radius.js' {
  declare module.exports: $Exports<'styled-system/dist/border-radius'>;
}
declare module 'styled-system/dist/border-width.js' {
  declare module.exports: $Exports<'styled-system/dist/border-width'>;
}
declare module 'styled-system/dist/box-shadow.js' {
  declare module.exports: $Exports<'styled-system/dist/box-shadow'>;
}
declare module 'styled-system/dist/clean-element.js' {
  declare module.exports: $Exports<'styled-system/dist/clean-element'>;
}
declare module 'styled-system/dist/color.js' {
  declare module.exports: $Exports<'styled-system/dist/color'>;
}
declare module 'styled-system/dist/constants.js' {
  declare module.exports: $Exports<'styled-system/dist/constants'>;
}
declare module 'styled-system/dist/disabled.js' {
  declare module.exports: $Exports<'styled-system/dist/disabled'>;
}
declare module 'styled-system/dist/flex-direction.js' {
  declare module.exports: $Exports<'styled-system/dist/flex-direction'>;
}
declare module 'styled-system/dist/flex-wrap.js' {
  declare module.exports: $Exports<'styled-system/dist/flex-wrap'>;
}
declare module 'styled-system/dist/flex.js' {
  declare module.exports: $Exports<'styled-system/dist/flex'>;
}
declare module 'styled-system/dist/focus.js' {
  declare module.exports: $Exports<'styled-system/dist/focus'>;
}
declare module 'styled-system/dist/font-size.js' {
  declare module.exports: $Exports<'styled-system/dist/font-size'>;
}
declare module 'styled-system/dist/font-weight.js' {
  declare module.exports: $Exports<'styled-system/dist/font-weight'>;
}
declare module 'styled-system/dist/hover.js' {
  declare module.exports: $Exports<'styled-system/dist/hover'>;
}
declare module 'styled-system/dist/index.js' {
  declare module.exports: $Exports<'styled-system/dist/index'>;
}
declare module 'styled-system/dist/justify-content.js' {
  declare module.exports: $Exports<'styled-system/dist/justify-content'>;
}
declare module 'styled-system/dist/letter-spacing.js' {
  declare module.exports: $Exports<'styled-system/dist/letter-spacing'>;
}
declare module 'styled-system/dist/line-height.js' {
  declare module.exports: $Exports<'styled-system/dist/line-height'>;
}
declare module 'styled-system/dist/prop-types.js' {
  declare module.exports: $Exports<'styled-system/dist/prop-types'>;
}
declare module 'styled-system/dist/pseudo-style.js' {
  declare module.exports: $Exports<'styled-system/dist/pseudo-style'>;
}
declare module 'styled-system/dist/remove-props.js' {
  declare module.exports: $Exports<'styled-system/dist/remove-props'>;
}
declare module 'styled-system/dist/responsive-style.js' {
  declare module.exports: $Exports<'styled-system/dist/responsive-style'>;
}
declare module 'styled-system/dist/space.js' {
  declare module.exports: $Exports<'styled-system/dist/space'>;
}
declare module 'styled-system/dist/style.js' {
  declare module.exports: $Exports<'styled-system/dist/style'>;
}
declare module 'styled-system/dist/text-align.js' {
  declare module.exports: $Exports<'styled-system/dist/text-align'>;
}
declare module 'styled-system/dist/theme.js' {
  declare module.exports: $Exports<'styled-system/dist/theme'>;
}
declare module 'styled-system/dist/util.js' {
  declare module.exports: $Exports<'styled-system/dist/util'>;
}
declare module 'styled-system/dist/width.js' {
  declare module.exports: $Exports<'styled-system/dist/width'>;
}
