// flow-typed signature: 3bd48c001a73e407f10c103d6f25d8d1
// flow-typed version: <<STUB>>/@storybook/storybook-deployer_v^2.3.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/storybook-deployer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/storybook-deployer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/storybook-deployer/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/storybook-deployer/src/utils.js' {
  declare module.exports: $Exports<'@storybook/storybook-deployer/src/utils'>;
}
